// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class IcuLib {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IcuLib(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IcuLib.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  diplomat_result_box_ICU4XLocale_ICU4XError ICU4XLocale_create_from_string(
    ffi.Pointer<ffi.Char> name_data,
    int name_len,
  ) {
    return _ICU4XLocale_create_from_string(
      name_data,
      name_len,
    );
  }

  late final _ICU4XLocale_create_from_stringPtr = _lookup<
      ffi.NativeFunction<
          diplomat_result_box_ICU4XLocale_ICU4XError Function(
              ffi.Pointer<ffi.Char>,
              ffi.Size)>>('ICU4XLocale_create_from_string');
  late final _ICU4XLocale_create_from_string =
      _ICU4XLocale_create_from_stringPtr.asFunction<
          diplomat_result_box_ICU4XLocale_ICU4XError Function(
              ffi.Pointer<ffi.Char>, int)>(isLeaf: true);

  diplomat_result_void_ICU4XError ICU4XLocale_basename(
    ffi.Pointer<ICU4XLocale> self,
    ffi.Pointer<DiplomatWriteable> write,
  ) {
    return _ICU4XLocale_basename(
      self,
      write,
    );
  }

  late final _ICU4XLocale_basenamePtr = _lookup<
      ffi.NativeFunction<
          diplomat_result_void_ICU4XError Function(ffi.Pointer<ICU4XLocale>,
              ffi.Pointer<DiplomatWriteable>)>>('ICU4XLocale_basename');
  late final _ICU4XLocale_basename = _ICU4XLocale_basenamePtr.asFunction<
      diplomat_result_void_ICU4XError Function(ffi.Pointer<ICU4XLocale>,
          ffi.Pointer<DiplomatWriteable>)>(isLeaf: true);

  ffi.Pointer<DiplomatWriteable> diplomat_buffer_writeable_create(
    int cap,
  ) {
    return _diplomat_buffer_writeable_create(
      cap,
    );
  }

  late final _diplomat_buffer_writeable_createPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<DiplomatWriteable> Function(ffi.Size)>>(
      'diplomat_buffer_writeable_create');
  late final _diplomat_buffer_writeable_create =
      _diplomat_buffer_writeable_createPtr
          .asFunction<ffi.Pointer<DiplomatWriteable> Function(int)>(
              isLeaf: true);

  void diplomat_buffer_writeable_destroy(
    ffi.Pointer<DiplomatWriteable> t,
  ) {
    return _diplomat_buffer_writeable_destroy(
      t,
    );
  }

  late final _diplomat_buffer_writeable_destroyPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<DiplomatWriteable>)>>(
      'diplomat_buffer_writeable_destroy');
  late final _diplomat_buffer_writeable_destroy =
      _diplomat_buffer_writeable_destroyPtr
          .asFunction<void Function(ffi.Pointer<DiplomatWriteable>)>(
              isLeaf: true);
}

final class diplomat_result_box_ICU4XLocale_ICU4XError extends ffi.Struct {
  external UnnamedUnion1 unnamed;

  @ffi.Bool()
  external bool is_ok;
}

final class UnnamedUnion1 extends ffi.Union {
  external ffi.Pointer<ICU4XLocale> ok;

  @ffi.UnsignedInt()
  external int errAsInt;

  ICU4XError get err => ICU4XError.fromValue(errAsInt);
}

final class ICU4XLocale extends ffi.Opaque {}

enum ICU4XError {
  ICU4XError_UnknownError(0),
  ICU4XError_WriteableError(1),
  ICU4XError_OutOfBoundsError(2),
  ICU4XError_Utf8Error(3),
  ICU4XError_DataMissingDataKeyError(256),
  ICU4XError_DataMissingVariantError(257),
  ICU4XError_DataMissingLocaleError(258),
  ICU4XError_DataNeedsVariantError(259),
  ICU4XError_DataNeedsLocaleError(260),
  ICU4XError_DataExtraneousLocaleError(261),
  ICU4XError_DataFilteredResourceError(262),
  ICU4XError_DataMismatchedTypeError(263),
  ICU4XError_DataMissingPayloadError(264),
  ICU4XError_DataInvalidStateError(265),
  ICU4XError_DataCustomError(266),
  ICU4XError_DataIoError(267),
  ICU4XError_DataUnavailableBufferFormatError(268),
  ICU4XError_DataMismatchedAnyBufferError(269),
  ICU4XError_LocaleUndefinedSubtagError(512),
  ICU4XError_LocaleParserLanguageError(513),
  ICU4XError_LocaleParserSubtagError(514),
  ICU4XError_LocaleParserExtensionError(515),
  ICU4XError_DataStructValidityError(768),
  ICU4XError_PropertyUnknownScriptIdError(1024),
  ICU4XError_PropertyUnknownGeneralCategoryGroupError(1025),
  ICU4XError_PropertyUnexpectedPropertyNameError(1026),
  ICU4XError_FixedDecimalLimitError(1280),
  ICU4XError_FixedDecimalSyntaxError(1281),
  ICU4XError_PluralsParserError(1536),
  ICU4XError_CalendarParseError(1792),
  ICU4XError_CalendarOverflowError(1793),
  ICU4XError_CalendarUnderflowError(1794),
  ICU4XError_CalendarOutOfRangeError(1795),
  ICU4XError_CalendarUnknownEraError(1796),
  ICU4XError_CalendarUnknownMonthCodeError(1797),
  ICU4XError_CalendarMissingInputError(1798),
  ICU4XError_CalendarUnknownKindError(1799),
  ICU4XError_CalendarMissingError(1800),
  ICU4XError_DateTimePatternError(2048),
  ICU4XError_DateTimeMissingInputFieldError(2049),
  ICU4XError_DateTimeSkeletonError(2050),
  ICU4XError_DateTimeUnsupportedFieldError(2051),
  ICU4XError_DateTimeUnsupportedOptionsError(2052),
  ICU4XError_DateTimeMissingWeekdaySymbolError(2053),
  ICU4XError_DateTimeMissingMonthSymbolError(2054),
  ICU4XError_DateTimeFixedDecimalError(2055),
  ICU4XError_DateTimeMismatchedCalendarError(2056),
  ICU4XError_TinyStrTooLargeError(2304),
  ICU4XError_TinyStrContainsNullError(2305),
  ICU4XError_TinyStrNonAsciiError(2306),
  ICU4XError_TimeZoneOffsetOutOfBoundsError(2560),
  ICU4XError_TimeZoneInvalidOffsetError(2561),
  ICU4XError_TimeZoneMissingInputError(2562),
  ICU4XError_TimeZoneInvalidIdError(2563),
  ICU4XError_NormalizerFutureExtensionError(2816),
  ICU4XError_NormalizerValidationError(2817),
  ICU4XError_InvalidCldrUnitIdentifierError(3072);

  final int value;
  const ICU4XError(this.value);

  static ICU4XError fromValue(int value) => switch (value) {
        0 => ICU4XError_UnknownError,
        1 => ICU4XError_WriteableError,
        2 => ICU4XError_OutOfBoundsError,
        3 => ICU4XError_Utf8Error,
        256 => ICU4XError_DataMissingDataKeyError,
        257 => ICU4XError_DataMissingVariantError,
        258 => ICU4XError_DataMissingLocaleError,
        259 => ICU4XError_DataNeedsVariantError,
        260 => ICU4XError_DataNeedsLocaleError,
        261 => ICU4XError_DataExtraneousLocaleError,
        262 => ICU4XError_DataFilteredResourceError,
        263 => ICU4XError_DataMismatchedTypeError,
        264 => ICU4XError_DataMissingPayloadError,
        265 => ICU4XError_DataInvalidStateError,
        266 => ICU4XError_DataCustomError,
        267 => ICU4XError_DataIoError,
        268 => ICU4XError_DataUnavailableBufferFormatError,
        269 => ICU4XError_DataMismatchedAnyBufferError,
        512 => ICU4XError_LocaleUndefinedSubtagError,
        513 => ICU4XError_LocaleParserLanguageError,
        514 => ICU4XError_LocaleParserSubtagError,
        515 => ICU4XError_LocaleParserExtensionError,
        768 => ICU4XError_DataStructValidityError,
        1024 => ICU4XError_PropertyUnknownScriptIdError,
        1025 => ICU4XError_PropertyUnknownGeneralCategoryGroupError,
        1026 => ICU4XError_PropertyUnexpectedPropertyNameError,
        1280 => ICU4XError_FixedDecimalLimitError,
        1281 => ICU4XError_FixedDecimalSyntaxError,
        1536 => ICU4XError_PluralsParserError,
        1792 => ICU4XError_CalendarParseError,
        1793 => ICU4XError_CalendarOverflowError,
        1794 => ICU4XError_CalendarUnderflowError,
        1795 => ICU4XError_CalendarOutOfRangeError,
        1796 => ICU4XError_CalendarUnknownEraError,
        1797 => ICU4XError_CalendarUnknownMonthCodeError,
        1798 => ICU4XError_CalendarMissingInputError,
        1799 => ICU4XError_CalendarUnknownKindError,
        1800 => ICU4XError_CalendarMissingError,
        2048 => ICU4XError_DateTimePatternError,
        2049 => ICU4XError_DateTimeMissingInputFieldError,
        2050 => ICU4XError_DateTimeSkeletonError,
        2051 => ICU4XError_DateTimeUnsupportedFieldError,
        2052 => ICU4XError_DateTimeUnsupportedOptionsError,
        2053 => ICU4XError_DateTimeMissingWeekdaySymbolError,
        2054 => ICU4XError_DateTimeMissingMonthSymbolError,
        2055 => ICU4XError_DateTimeFixedDecimalError,
        2056 => ICU4XError_DateTimeMismatchedCalendarError,
        2304 => ICU4XError_TinyStrTooLargeError,
        2305 => ICU4XError_TinyStrContainsNullError,
        2306 => ICU4XError_TinyStrNonAsciiError,
        2560 => ICU4XError_TimeZoneOffsetOutOfBoundsError,
        2561 => ICU4XError_TimeZoneInvalidOffsetError,
        2562 => ICU4XError_TimeZoneMissingInputError,
        2563 => ICU4XError_TimeZoneInvalidIdError,
        2816 => ICU4XError_NormalizerFutureExtensionError,
        2817 => ICU4XError_NormalizerValidationError,
        3072 => ICU4XError_InvalidCldrUnitIdentifierError,
        _ => throw ArgumentError("Unknown value for ICU4XError: $value"),
      };
}

final class diplomat_result_void_ICU4XError extends ffi.Struct {
  external UnnamedUnion2 unnamed;

  @ffi.Bool()
  external bool is_ok;
}

final class UnnamedUnion2 extends ffi.Union {
  @ffi.UnsignedInt()
  external int errAsInt;

  ICU4XError get err => ICU4XError.fromValue(errAsInt);
}

final class DiplomatWriteable extends ffi.Struct {
  external ffi.Pointer<ffi.Void> context;

  external ffi.Pointer<ffi.Char> buf;

  @ffi.Size()
  external int len;

  @ffi.Size()
  external int cap;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<DiplomatWriteable>)>>
      flush;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<DiplomatWriteable>, ffi.Size)>> grow;
}
