name: bindings_generator
description: bindings generator for icu4x
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  path: ^1.8.3
  ffigen: ^9.0.1
  yaml: ^3.1.2
  collection: ^1.18.0
  recase: ^4.1.0
  code_builder: ^4.7.0
  dart_style: ^2.3.3

dev_dependencies:
  lints: ^2.1.1

