include: package:lints/recommended.yaml

analyzer:
  language:
    strict-inference: true
    strict-casts: true
    strict-raw-types: true

  exclude:
    - "gen/**"
    - "icu4x/**"
    - "generated_bindings.dart"

linter:
  rules:
    prefer_single_quotes: true
    # TODO(nikitadol): need remove
    constant_identifier_names: false
    # TODO(nikitadol): need remove
    non_constant_identifier_names: false
    require_trailing_commas: true
    collection_methods_unrelated_type: true
    unrelated_type_equality_checks: true
