name: root

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.0
    dependencies:
      path: ^1.9.0
    dev_dependencies:
      lints: ^5.0.0
      test: ^1.25.8
      benchmark_runner: ^1.0.0
