name: root
description: tools for repo
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  meta: ^1.15.0
  path: ^1.9.0
  tar: ^2.0.0
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  ffigen: ^13.0.0
  melos: ^6.1.0
