name: _tools
description: tools for repo
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0
  path: ^1.8.3
  tar: ^1.0.1
  http: ^1.1.0

  bindings_generator:
    path: packages/bindings_generator

dev_dependencies:
  lints: ^2.1.1


  test: ^1.24.7
