name: icu4d
description: icu4x wrapper
version: 0.0.1
repository: https://github.com/nikitadol/icu4d

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: any
  meta: any

  ffi: ^2.1.2

dev_dependencies:
  lints: ^4.0.0

  path: ^1.9.0
  tar: ^2.0.0

  test: ^1.25.8
  benchmark_harness: any
