name: icu4d
description: icu4x wrapper
version: 0.0.1
repository: https://github.com/nikitadol/icu4d

environment:
  sdk: ^3.5.0

dependencies:
  meta: '>= 1.14.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
