name: bench
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  benchmark_runner: ^1.0.0
