name: _tools
description: idu4d utils
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tar: ^2.0.0
  dio: ^5.7.0
  path: ^1.9.1
  recase: ^4.1.0
  ffigen: ^16.0.0
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  yaml: any
  glob: any
  collection: any

dev_dependencies:
  lints: ^5.0.0

ffigen:
  name: IcuLib
  output: ../icu4d/lib/src/ffi/generated_bindings.dart
  exclude-all-by-default: true
  headers:
    entry-points:
      - ../../icu4x/ffi/capi/bindings/c/**.h
      - lib/fixed_diplomat_runtime.h
  ignore-source-errors: true
  structs:
    rename:
      'DiplomatWriteable': 'ICU4XDiplomatWriteable'
  functions:
    symbol-address:
      include:
        - .*_destroy
    leaf:
      include:
        - .*
    include:
      - diplomat_buffer_writeable_create
      - diplomat_buffer_writeable_destroy
      - ICU4XLocale_create_from_string
      - ICU4XLocale_create_und
      - ICU4XLocale_basename
      - ICU4XLocale_to_string
      - ICU4XLocale_basename
      - ICU4XLocale_get_unicode_extension
      - ICU4XLocale_language
      - ICU4XLocale_set_language
      - ICU4XLocale_region
      - ICU4XLocale_set_region
      - ICU4XLocale_script
      - ICU4XLocale_set_script
      - ICU4XLocale_destroy
